name: throws
description: An annotation for documenting and enforcing throwing functions.
version: 1.0.0-alpha.3
repository: https://github.com/Yobari-Timeliners/throws/tree/main/packages/throws
homepage: https://github.com/Yobari-Timeliners/throws/tree/main/packages/throws
screenshots:
  - description: 'Balling errors'
    path: 'art/logo.png'

environment:
  sdk: ^3.10.0

dev_dependencies:
  lints: ^6.0.0
