name: throws_plugin
description: Analyzer plugin for @Throws/@throws usage.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.10.0

dependencies:
  analysis_server_plugin: ^0.3.0
  analyzer_plugin: ^0.13.0
  analyzer: ^8.0.0
  throws:
    path: ../throws

dev_dependencies:
  lints: ^6.0.0
  analyzer_testing: ^0.1.5
  test_reflective_loader: ^0.2.0
  test: ^1.25.0
